# Generated by Django 5.2.17 on 2026-09-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='mombre',
            new_name='nombre',
        ),
    ]
