# Generated by Django 5.2.17 on 2026-09-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='clasificiacion',
            new_name='clasificacion',
        ),
    ]
